questions:
  - question 1: מהי ההגדרה של קוד פתוח?
    answer: קוד פתוח מתייחס לתוכנות או ספריות שהקוד שלהן זמין לציבור, כך שכל אחד יכול לצפות, לערוך, ולהפיץ אותו.

  - question 2: מה היתרונות המרכזיים של קוד פתוח?
    answer: שקיפות, גמישות, קהילה תומכת, עלויות נמוכות ושיפור מתמיד על ידי קהילה גלובלית.

  - question 3: מהו ההבדל העיקרי בין רישיון MIT לרישיון GPL?
    answer: רישיון MIT גמיש יותר ומאפשר שימוש בקוד גם בפרויקטים סגורים, בעוד GPL מחייב שכל תוכנה המשתמשת בקוד זה תהיה בקוד פתוח.

  - question 4: 
      האם קוד פתוח הוא תמיד חינמי? 
    answer: 
      לא. למרות שהקוד עצמו חינמי, ייתכן שתהיינה עלויות נוספות כגון תמיכה, תחזוקה או שירותים נלווים.

  - question 5: 
      מהי מערכת הקוד הפתוח GitHub ומה תפקידה?
    answer: 
      GitHub היא פלטפורמה לניהול קוד ומאגרי קוד פתוח. היא מאפשרת לצוותים לשתף פעולה, לבצע בקרת גרסאות, ולנהל פרויקטים.

  - question 6: מהו רישיון Apache 2.0? 
    options:
      - רישיון שמגביל שימוש מסחרי
      - רישיון שמאפשר שימוש חופשי בקוד כולל לצרכים מסחריים
      - רישיון שמתמקד בהגנה על פטנטים
      - רישיון שמאפשר שימוש רק למטרות אקדמיות
    answer: רישיון שמאפשר שימוש חופשי בקוד כולל לצרכים מסחריים

  - question 7: 
      איזו ספריית קוד פתוח תומכת בלימוד מכונה? 
    options:
      - TensorFlow
      - React
      - Bootstrap
      - Flask
    answer: TensorFlow

  - question 8: מה היתרון העיקרי של שימוש בקוד פתוח עבור מפתחים צעירים? 
    options:
      - עלות נמוכה
      - נגישות לקוד מוכן ללמידה והתנסות
      - אין צורך ללמוד רישיונות
      - קהילה קטנה שמספקת תמיכה אישית
    answer: נגישות לקוד מוכן ללמידה והתנסות

  - question 9: כיצד קהילת קוד פתוח תורמת לשיפור הפרויקט? 
    answer: הקהילה מגלה באגים, מוסיפה פיצ'רים חדשים, ומשפרת את הקוד דרך שיתופי פעולה גלובליים.

  - question 10: 
      מהי המשמעות של "Contributor" בקוד פתוח?
    options:
      - משתמש שרק מוריד את הקוד
      - משתמש שרוכש רישיון
      - אדם שתורם שינויים או הצעות לקוד
      - מפתח שמתחזק את הקוד לבד
    answer: אדם שתורם שינויים או הצעות לקוד

 - question 11: 
      איזה מבין הרישיונות הבאים אינו רישיון קוד פתוח?
    options:
      - Apache License
      - GNU GPL
      - MIT License
      - Microsoft EULA
    answer: Microsoft EULA

 - question 12: 
     כיצד ניתן להבטיח עמידה בתנאי רישיון הקוד הפתוח?
    options:
      - על ידי רכישת רישיון מסחרי מהחברה המפתחת
      - על ידי קריאה והבנה של תנאי הרישיון
      - על ידי שימוש בקוד ללא שינו
      - על ידי אי-הפצת הקוד כלל
    answer: על ידי קריאה והבנה של תנאי הרישיון

